[build-system]
requires = [
    "setuptools",
    "wheel",
    "Cython",
    "numpy<3.0.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "NumCircBuf"
dynamic = [
    "version",
    "description",
    "authors",
    "readme",
    "license",
    "keywords",
    "classifiers",
    "dependencies",
    "optional-dependencies",
    "requires-python",
]

[project.urls]
Homepage = "https://github.com/basimali-ai/NumCircBuf"
Repository = "https://github.com/basimali-ai/NumCircBuf"
Changelog = "https://github.com/basimali-ai/NumCircBuf/blob/main/docs/CHANGELOG.md"
Issues = "https://github.com/basimali-ai/NumCircBuf/issues"

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.cibuildwheel]
test-requires = ["pytest", "pytest-mock", "numpy<3.0.0", "cython"]
before-test = [
    'pip install setuptools "numpy<3.0.0" cython',
    'ONLY_TEST_API=1 python setup.py build_ext --inplace'
]
test-command = "PYTHONPATH={project}/src/numcircbuf pytest {project}/tests"

[[tool.cibuildwheel.overrides]]
select = "*-win*"
test-requires = ["pytest", "pytest-mock", "numpy^<3.0.0", "cython"]
before-test = [
    'pip install setuptools "numpy<3.0.0" cython',
    'set ONLY_TEST_API=1&& python setup.py build_ext --inplace'
]
test-command = "set PYTHONPATH={project}/src/numcircbuf&& pytest {project}/tests"

[tool.mypy]
python_version = "3.11"
files = "numcircbuf"
exclude = ".*\\.pyx|.*\\.pxd"
ignore_missing_imports = true
strict = true
follow_imports = "silent"
untyped_calls_exclude = ["Cython"]

[[tool.mypy.overrides]]
module = ["tests.*", "perf.*"]
strict = false
disallow_untyped_calls = false
disable_error_code = [
    "call-overload",
    "var-annotated",
    "type-arg",
    "no-untyped-def"
]

[tool.ruff.lint]
ignore = ["DTZ005", "PYI041", "UP007"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["BLE001"]
"perf/**/*.py" = ["BLE001"]

[tool.pytest.ini_options]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"
addopts = "-vv"
testpaths = ["tests"]

[tool.coverage.run]
plugins = ["Cython.Coverage"]
source = ["src"]
omit = [
    "*/_build_helpers.py",
    "*/_test_cython_api.pyx",
]

[tool.coverage.paths]
source = [
    "src",
    "*/src",
]

[tool.coverage.report]
omit = [
    "*/_build_helpers.py",
    "*/_test_cython_api.pyx",
]
